### ISSUE TITLE
Review results capped at 200 despite limit placed at 1000

### ISSUE THREAD

**Issue by mel-hsw** [katacek/google-play-reviews#3]
Requesting 1000 review pull but only getting 200. 

Request: 
{
  "appUrl": "https://play.google.com/store/apps/details?id=com.nick.noggin&hl=en_US&gl=US",
  "appId": "com.nick.noggin",
  "limit": 1000
}

**Comment by katacek** [comment]
Hey, thanks for reporting it! 
Fixed by commit #82bcd8729d9feadecef7c125686569fbe56fa8b2.
